#!/usr/bin/env node

var udp = require('dgram').createSocket('udp4'),
    net = require('net'),
    port = process.env.PHANT_REPEATER_PORT || 5000,
    clients = [];

net.createServer(function(stream) {

  clients.push(stream);

  stream.on('error', function() {
    var index = clients.indexOf(stream);
    clients.splice(index, 1);
    stream.end();
  });

  stream.on('end', function() {
    var index = clients.indexOf(stream);
    clients.splice(index, 1);
  });

}).listen(process.env.PHANT_REPEATER_PORT || 5000, process.env.PHANT_REPEATER_HOST || 'localhost');

udp.on('message', function(message) {

  clients.forEach(function(client) {
    client.write(message);
  });

});

udp.bind(process.env.PHANT_REPEATER_PORT || 5000);

console.log('RELAYING TO TCP PORT ' + port);
